### ISSUE TITLE
Cookie Feature for GDPR Compliance

### ISSUE THREAD

**Issue by ArnabBCA** [InternetHealthReport/ihr-website#732] opened 2024-01-08 14:49 UTC
**Is your feature request related to a problem? Please describe.**
As stated by @dpgiakatos in #669 There is a need for Cookie Consent Banner for GDPR Compliance

**Describe the solution you'd like**
There would be a popup with message, accept and decline button when the user visits the website. if clicked on the accept button a function will run to store the user cookie preference. 

For example a Boolean value set to true in the local storage (cookie_preference=true) for future needs. Also any immediate value or cookie would we set in the browser after clicking the accept button.

Currently The Website uses local storage to set the language preference. So this will be handled in the function when the accept button is clicked as mentioned above.

https://quasar.dev/quasar-plugins/notify#example--multiline This Quasar library Can be used for the popup message.

**Comment by dpgiakatos** [comment] 2024-01-09 12:22
Let's use a dialog that will open in the bottom position. Additionally, the dialog should not be closed if the user clicks outside the dialog. It should only close when the user clicks the accept or decline button.

Please provide some mockups in which you will explain how you are thinking of designing the feature.

**Comment by ArnabBCA** [comment] 2024-01-09 13:51
@dpgiakatos these are some design which can be used, personally i like the design 1 cause it is less distracting and does not cover much of the website.
Design 1.

![Design 1](https://github.com/InternetHealthReport/ihr-website/assets/113178195/aaaf9d95-51f0-4a5d-bf63-bdb87c3dc494)
Design 2
In Design 2 the particular dialog which you have suggested doesnot provide (bottom-right) postion only bottom position can be used.
![Design 2](https://github.com/InternetHealthReport/ihr-website/assets/113178195/635a31aa-4fc5-44e9-a3ea-fa078c1036e4)

Also both the design look almost similar in mobile devices so i have not provided.

@dpgiakatos I have a question suppose a user declines the popup will show again if the website is refreshed or visited again am i right?

**Comment by dpgiakatos** [comment] 2024-01-09 16:21
We want the cookie banner to be attention-grabbing (we want the user to be alert and view the message) because we seek the user's consent to use cookies and storage. Therefore, we will proceed with the second design, and we can use CSS to move the dialog to the bottom-right.

If the user accepts the cookies, the banner should be removed. If the user declines the cookies, the banner should also be removed, but only for the current session. If the page is refreshed or visited again, the banner should be shown again (as per your question).

Additionally, if the user declines the cookies, the application must not use any cookies or local storage. Therefore, we should ensure that the application does not crash in this scenario.

**Comment by ArnabBCA** [comment] 2024-01-09 16:44
@dpgiakatos yeah I agree with you let me know so that I can start working on it

**Comment by dpgiakatos** [comment] 2024-01-09 17:17
Before you start working on it, please provide a detailed explanation of the architecture for this new feature. Specify what new files will be added, how it will be connected with the rest of the app, whether we need a custom Vue plugin like IhrApi.js, which can be used throughout the app using the inject function, etc.

**Comment by ArnabBCA** [comment] 2024-01-11 08:27
1. The Custom vue component will be created with the name (CookieBanner.vue) and placed in the components folder
2.  The CookieBanner.vue will be imported in the App.vue component and placed bottom in the template.
3.  Custom props allowed by Quasar will be needed like 
(**persistent**) _User cannot dismiss Dialog if clicking outside of it or hitting ESC key; Also, an app route change won't dismiss it_
(**no-shake** ) _Do not shake up the Dialog to catch user's attention_
(**seamless**) _Put Dialog into seamless mode; Does not use a backdrop so user is able to interact with the rest of the page too_
4. Few CSS Class to match with the Design 2 as discussed.

### App Mounted
When the App is mounted a funtion will run it will first check 
```
if(localStorage.getItem("cookie_preference") === null){
    openDialog();
}
```
If it is not null that means "**cookie_preference**" is **true** then it will not open the dialog
### Accept Button is Clicked
If accept Button is Clicked a function will run to set a localstorage value( "cookie_preference" = true) and another function to close the Dialog
### Decline Button is Clicked
If Decline Button is Clicked a function will run to close the dialog

### Handling Other Cookies or Local Storage
When we Need to apply any cookie or put some value in local storage we can just check the localstorage for cookie prefference if it is true we can set value or it is null then it will not set.

### Is Vue Plugin Required?
For Just Cookie Preference I don't think we need any Vue Plugin because it will be used only when the App is Mounted.

**Comment by ArnabBCA** [comment] 2024-01-11 08:29
@dpgiakatos pls review it.

**Comment by dpgiakatos** [comment] 2024-01-11 10:29
The architecture that you propose is good, but I cannot assign this to you yet because you have too many issues assigned (7 issues), with 4 of them connected to pull requests awaiting review and 3 issues still unresolved. Please resolve the other issues first.

**Comment by RickDeb2004** [comment] 2024-01-11 10:40
@dpgiakatos can I work on it ..I have knowledge in this specific issue...can you assign me?

**Comment by RickDeb2004** [comment] 2024-01-11 10:41
> @dpgiakatos can I work on it ..I have knowledge in this specific issue...can you assign me?

As no issue is assigned to me 🥺 earlier

**Comment by ArnabBCA** [comment] 2024-01-11 10:42
@dpgiakatos issue #672 is solved and merged, issue #684 need this feature to be implemented first because theme toggle requires localStorage and issue #673 i am closing because it related to backend and Swagger UI.

**Comment by ArnabBCA** [comment] 2024-01-11 10:49
> @dpgiakatos can I work on it ..I have knowledge in this specific issue...can you assign me?

Brother I have already worked on it and created a working demo.

**Comment by dpgiakatos** [comment] 2024-01-11 10:59
Since you already have a working demo, I am assigning this to you. However, for future tasks, please refrain from starting implementation before receiving an assignment.

**Comment by RickDeb2004** [comment] 2024-01-11 11:15
@dpgiakatos if you have no problem , can you assign me other three 

> The architecture that you propose is good, but I cannot assign this to you yet because you have too many issues assigned (7 issues), with 4 of them connected to pull requests awaiting review and 3 issues still unresolved. Please resolve the other issues first.

@dpgiakatos if you have no problem , can you assign me those three unresolve issue...coz want to help you .

**Comment by ArnabBCA** [comment] 2024-01-11 11:19
> @dpgiakatos if you have no problem , can you assign me other three
> 
> > The architecture that you propose is good, but I cannot assign this to you yet because you have too many issues assigned (7 issues), with 4 of them connected to pull requests awaiting review and 3 issues still unresolved. Please resolve the other issues first.
> 
> @dpgiakatos if you have no problem , can you assign me those three unresolve issue...coz want to help you .

One is merged other one is also done i just have to modify it to align it with this feature. You can work on issue #673

**Comment by RickDeb2004** [comment] 2024-01-11 11:41
> 1. The Custom vue component will be created with the name (CookieBanner.vue) and placed in the components folder
> 2. The CookieBanner.vue will be imported in the App.vue component and placed bottom in the template.
> 3. Custom props allowed by Quasar will be needed like
>    (**persistent**) _User cannot dismiss Dialog if clicking outside of it or hitting ESC key; Also, an app route change won't dismiss it_
>    (**no-shake** ) _Do not shake up the Dialog to catch user's attention_
>    (**seamless**) _Put Dialog into seamless mode; Does not use a backdrop so user is able to interact with the rest of the page too_
> 4. Few CSS Class to match with the Design 2 as discussed.
> 
> ### Dialog Message
> I have Copied the Quasar Cookie Preference we can change it after discussing
> 
> > Our third-party tools use cookies, which are necessary for its functioning and required to achieve the purposes illustrated in the cookie policy.
> 
> ### App Mounted
> When the App is mounted a funtion will run it will first check
> 
> ```
> if(localStorage.getItem("cookie_preference") === null){
>     openDialog();
> }
> ```
> 
> If it is not null that means "**cookie_preference**" is **true** then it will not open the dialog
> 
> ### Accept Button is Clicked
> If accept Button is Clicked a function will run to set a localstorage value( "cookie_preference" = true) and another function to close the Dialog
> 
> ### Decline Button is Clicked
> If Decline Button is Clicked a function will run to close the dialog
> 
> ### Handling Other Cookies or Local Storage
> When we Need to apply any cookie or put some value in local storage we can just check the localstorage for cookie prefference if it is true we can set value or it is null then it will not set.
> 
> ### Is Vue Plugin Required?
> For Just Cookie Preference I don't think we need any Vue Plugin because it will be used only when the App is Mounted.
> 
> ### Other File Changes
> At present we only need to modify the switchLanguage function in the translation.js file to align with this feature.

@dpgiakatos here I just have done some research on @ArnabBCA 's proposal , his proposal looks so well thought but still I found some potential bugs ..that can be considered according to me.
1. **Dialog Not Appearing on First Visit:**
   - **Issue:** If the user visits the site for the first time, the `localStorage.getItem("cookie_preference")` check will return null, and the dialog won't appear.
   - **Solution:** Instead of checking for `null`, check if the value is `undefined` to ensure the dialog appears on the first visit, it can enhance the situation .
     ```javascript
     if (localStorage.getItem("cookie_preference") === undefined) {
         openDialog();
     }
     ```

2. **Handling Other Cookies or Local Storage:**
   - **Issue:** If you only check for the presence of "cookie_preference" to determine whether to set other cookies or values in local storage, it might lead to unexpected behavior.
   - **Solution:** Consider having a more specific check for each feature that requires local storage or cookies. This way, you have better control over the dependencies.
     ```javascript
     if (localStorage.getItem("cookie_preference") === true) {
         // now we can set some cookies in local storage.
     }
     ```

3. **Accept Button Clicked - Setting Cookie Preference:**
   - **Issue:** When the accept button is clicked, you set the value in local storage, but you also need to check and handle the case where the user has already accepted cookies in a previous session.
   - **Solution:** Modify the logic to check for existing preference and only set the value if it's not already set.
     ```javascript
     if (localStorage.getItem("cookie_preference") === null) {
         localStorage.setItem("cookie_preference", true);
         closeDialog();
     }
     ```

4. **Decline Button Clicked - Closing Dialog:**
   - **Issue:** When the decline button is clicked, you need to close the dialog, but you also want to handle the scenario where the user has previously accepted cookies.
   - **Solution:** Modify the logic to close the dialog regardless of the existing preference.
     ```javascript
     closeDialog();
     ```

5. **Make sure Consistent Dialog Display Across Pages:**
   
6.** Browser inconsistencies may lead to unexpected behavior, for that we can use BrowserStack or cross-browser.**

**Comment by ArnabBCA** [comment] 2024-01-11 11:47
When the app mounts if there is no variable name cookie_preference in local  storage (null) that means the user has not accepted the consent so the dialog will appear

**Comment by dpgiakatos** [comment] 2024-01-11 11:54
@ArnabBCA The PR #719 upgrades some packages to the latest version, so some components may not work. Therefore, before opening a new PR, please wait for the merge of #719.

**Comment by RickDeb2004** [comment] 2024-01-11 12:02
> @RickDeb2004 When the app mounts if there is no variable name cookie_preference in local storage (null) that means the user has not accepted the consent so the dialog will appear. Everything is working as expected in my local machine.

 checking for null in local storage might not be the most accurate way to determine if the user has not accepted the consent. It's possible that other values, including undefined or false, could be present in the local storage for the "cookie_preference" key, leading to inconsistent behavior.

**Comment by RickDeb2004** [comment] 2024-01-11 12:51
@dpgiakatos as I see no hurry to raise a new PR until #719 is getting merged, I would like to add some new implementations..that can enhance user experience :

- **Animations for Attention**:

  Implement subtle animations or transitions to make the cookie banner more attention-grabbing. For example, you can add a fade-in or slide-in animation when the banner appears.

-  **Delay Display Option**:
    Provide an option to delay the initial display of the cookie banner. Some users might prefer to interact with the site content before being prompted with the cookie consent.

- **Automated Cookie Expiry**:
   Set automatic expiry for the session-based cookie consent. After a certain duration or when the browser is closed, the user's decline preference can reset, prompting the banner on their next visit.

@dpgiakatos what's your thought on these

**Comment by ArnabBCA** [comment] 2024-01-11 12:59
Quasar Dialog library has default animation you can see on the official website and At present no cookie is used in the website

**Comment by dpgiakatos** [comment] 2024-01-12 05:04
> @dpgiakatos as I see no hurry to raise a new PR until #719 is getting merged, I would like to add some new implementations..that can enhance user experience :
> 
> * **Animations for Attention**:
>   Implement subtle animations or transitions to make the cookie banner more attention-grabbing. For example, you can add a fade-in or slide-in animation when the banner appears.
> * **Delay Display Option**:
>   Provide an option to delay the initial display of the cookie banner. Some users might prefer to interact with the site content before being prompted with the cookie consent.
> * **Automated Cookie Expiry**:
>   Set automatic expiry for the session-based cookie consent. After a certain duration or when the browser is closed, the user's decline preference can reset, prompting the banner on their next visit.
> 
> @dpgiakatos what's your thought on these

No, let's stick to the initial plan.

**Closed** 2024-03-06 05:11 UTC
Labels: enhancement
