### ISSUE TITLE
Update the code to vue.js 3

### ISSUE THREAD

**Issue by ConnectBhawna** [InternetHealthReport/ihr-website#479] opened 2023-05-29 04:14 UTC
**Is your feature request related to a problem? Please describe.**
Updating the codebase to Vue.js 3 brings several benefits and reasons why it is necessary:
1) Improved Performance
2) Composition API
3) Smaller Bundle Size
4) Better TypeScript Support
5) Official Composition API
6) Ecosystem Compatibility
and many more

**Describe alternatives you've considered**
For updating the codebase into Vue.js 3 . I will follow the certain approach :-
1) Upgrade Vue CLI: Ensure you have the latest version of Vue CLI installed globally on your system by running npm install -g @vue/cli.

2) Create a New Vue.js 3 Project: Use Vue CLI to create a new Vue.js 3 project by running vue create <project-name>. Choose the default preset or manually select features based on your project requirements.

3) Copy Existing Code: Copy your existing code files, including components, templates, styles, and Vuex store files, into the corresponding directories of the newly created Vue.js 3 project.

4) Update Dependencies: Update your project's dependencies in the package.json file to the Vue.js 3 compatible versions. Specifically, update the vue, vue-router, and vuex packages. Refer to the official documentation or package repositories for the compatible versions.

5) Update Composition API: Vue.js 3 introduces the Composition API, so you'll need to update your component code to use it. Refactor your existing Options API code (e.g., data(), methods, computed, etc.) to use the Composition API's setup() function. Move relevant code to reusable composition functions and return the necessary reactive variables and functions from setup().

6) Update Template Syntax: Vue.js 3 introduces a few changes to the template syntax. For example, v-bind is replaced by :, and v-on is replaced by @. Update your templates accordingly to use the new syntax.

7) Modify Lifecycle Hooks: Vue.js 3 renames and restructures some of the lifecycle hooks. Review your component's lifecycle hooks and update them to the new equivalents. For example, beforeMount becomes onBeforeMount and beforeUpdate becomes onBeforeUpdate.

8) Update Vuex Store: If you're using Vuex, update your store code to the Vue.js 3 syntax. For example, replace createStore with createStore and modify any references to Vuex store properties or methods according to the new syntax.

9) Test and Refactor: Test your code thoroughly after the conversion process to ensure everything is working as expected. Refactor any code that may have compatibility issues or is no longer necessary due to changes in Vue.js 3.

**Additional context**
I am currently working on this issue. Issue being approved by Romain Sir :)

**Comment by romain-fontugne** [comment] 2023-06-07 02:49
Thanks, let's us know how it goes :)

(this is a duplicate of #469)

**Closed** 2023-06-07 04:40 UTC
