### ISSUE TITLE
Navbar menu tag is not visible clearly 

### ISSUE THREAD

**Issue by weberankit** [InternetHealthReport/ihr-website#234] opened 2023-01-07 04:59 UTC
Navbar menu tag is not visible clearly ,Home page
![chrome_ucK57XjbEO](https://user-images.githubusercontent.com/94105514/211131822-ab23e86a-e976-48a0-a81e-56cf175bf9b5.png)

**Comment by weberankit** [comment] 2023-01-07 05:01
Hi! I'm working on this issue plz assign this  to me

**Comment by Aniket762** [comment] 2023-01-07 05:30
> Navbar menu tag is not visible clearly ,Home page ![chrome_ucK57XjbEO](https://user-images.githubusercontent.com/94105514/211131822-ab23e86a-e976-48a0-a81e-56cf175bf9b5.png)

Hey, I am not able to reproduce the following bug. Would have been great, if you could have written the steps to reproduce the bug. Following the issue template. 

Also, the deployed application looks perfect to me: https://ihr.iijlab.net/ihr/en-us/

Thus, closing the issue

**Closed by Aniket762** 2023-01-07 05:30 UTC

**Comment by weberankit** [comment] 2023-01-08 11:59
Thanks for the review. I have checked the website right now perfectly working but I think there is some issue as 
when I try to open the website using the link ihr.iijlab.net its shows the following bug for a few seconds after a second it disappears but that doesn't matter maybe it takes some time to set up page
checkout video at 0.8s

https://user-images.githubusercontent.com/94105514/211194754-4535f63d-50b0-4087-9594-4bb7f6753102.mp4

**Comment by Aniket762** [comment] 2023-01-08 12:53
> Thanks for the review. I have checked the website right now perfectly working but I think there is some issue as when I try to open the website using the link ihr.iijlab.net its shows the following bug for a few seconds after a second it disappears but that doesn't matter maybe it takes some time to set up page checkout video at 0.8s
> 
>  dVKJDUnx56.mp4

Not able to see the bug :(
