### ISSUE TITLE
Wrong 'Direct Neighbour' initial status

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#75] opened 2022-03-29 08:16 UTC
**Describe the bug**
A click on the AS dependency graph shows a detailed table that include a column called 'Direct Neighbour'. These values are wrong if we click too quickly on the graph (e.g. when the page is still loading). The data for this column is fetch by an API call to RIPE stat, if the API call is not complete then all direct neighbor values are displayed as 'x'.

**To Reproduce**

1. Go to https://ihr.iijlab.net/ihr/en-us/networks/AS2497
2. Click as fast as possible on a line of the top graph (AS Dependency)
3. See the all the 'x' values in Direct neighbour. If we click again on the graph (after the page is fully loaded) some of these 'x' become 'v' which is the expected results.

**Expected behavior**
We should show spinning wheels in the direct neighbour column to let the user know that the data is still loading.

**Desktop (please complete the following information):**

- OS: linux
- Browser: brave

**Comment by Akshaykoushik06** [comment] 2022-04-04 15:16
@romain-fontugne I tried to reproduce the issue. After clicking on a line of the top graph, sometimes it takes a lot of time for the data to load in the table below. Sometimes it loads quicker. Am I not reproducing the issue correctly?

**Comment by Adityasaini10012001** [comment] 2022-12-26 18:01
hey @Aniket762 assign this to me

**Comment by Aniket762** [comment] 2022-12-26 19:10
> hey @Aniket762 assign this to me

go for it

**Comment by pankaj87072** [comment] 2022-12-29 17:50
@Adityasaini10012001 are you working on it

**Comment by pankaj87072** [comment] 2022-12-29 17:53
@Aniket762 can you please tell me why no one solved the issues opened since many months

**Comment by Adityasaini10012001** [comment] 2022-12-29 18:11
@pankaj87072  yes I am working on it

**Comment by Rishi-srk** [comment] 2023-01-15 17:16
Hey @Aniket762 can u assign this issue to me

**Comment by Adityasaini10012001** [comment] 2023-01-15 18:52
@Rishi-srk I am working on it.

**Comment by harish343** [comment] 2023-01-25 15:48
if issue is fullfilled then close this issue

**Comment by romain-fontugne** [comment] 2023-02-22 07:39
Any update on this?

**Comment by Sukriti-m** [comment] 2023-03-06 12:52
Hey @romain-fontugne 
I'd like to work on this issue. If there is no recent update, can you please assign it to me?

**Comment by romain-fontugne** [comment] 2023-03-07 05:11
@Adityasaini10012001 any update on this? let us know if you have any problem fixing this issue or if you gave up on it

**Comment by J0SAL** [comment] 2023-03-09 15:47
Hello @romain-fontugne sir, if no one's working on it, can you assign it to me

**Comment by junaidhussain49** [comment] 2023-03-10 22:35
Hello @romain-fontugne  can you assign this to me if no one is working?

**Comment by romain-fontugne** [comment] 2023-03-13 02:29
@Adityasaini10012001 any update on this? let us know if you have any problem fixing this issue or if you gave up on it

**Comment by anugcodes** [comment] 2023-04-08 09:27
hey @Adityasaini10012001 are you still working on it? , I think i have figured a solution. 
@romain-fontugne  sir, the  `asnNeighbours`  data has to be loaded only once at the page load, so i think we can add a variable that tracks the loading status of the `asnNeighbours`  after that we can delay the loading of both for `dependency` and `dependent` tables, which will affect the loading of tables for first time only.
also i think showing spinning wheels in the direct neighbour column is not necessary since it occurs once only and it will rather increase the complexity of the problem.
what do you say?

**Comment by romain-fontugne** [comment] 2023-04-19 07:03
we had no update from @Adityasaini10012001 for over a month. I think we can reassign this issue. @anugcodes the preloading solution you propose makes sense. Feel free to work on it

**Closed** 2023-06-07 03:02 UTC
Labels: bug, help wanted, good first issue, beginner-friendly, javascript
