### ISSUE TITLE
Build Failure with Python 3.11.X

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/ihr-website#568] opened 2023-08-30 15:00 UTC
**Describe the bug**
Building the Project failed with Python 3.11.X:
```
npm ERR! code 1
npm ERR! path /Users/mohamedawnallah/Desktop/ihr-website/node_modules/deasync
npm ERR! command failed
npm ERR! command sh -c node ./build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.9.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.11.4 found at "/Users/mohamedawnallah/.pyenv/versions/3.11.4/bin/python3"
npm ERR! (node:67089) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Users/mohamedawnallah/.pyenv/versions/3.11.4/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mohamedawnallah/Desktop/ihr-website/node_modules/deasync/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mohamedawnallah/Library/Caches/node-gyp/16.9.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/mohamedawnallah/Library/Caches/node-gyp/16.9.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/mohamedawnallah/Library/Caches/node-gyp/16.9.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/mohamedawnallah/Desktop/ihr-website/node_modules/deasync',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!              ^^^^^^^^^^^^^^^^^
npm ERR!   File "/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!            ^^^^^^^^^^^^^^^^^^
npm ERR!   File "/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
npm ERR!     return gyp_main(args)
npm ERR!            ^^^^^^^^^^^^^^
npm ERR!   File "/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 629, in gyp_main
npm ERR!     [generator, flat_list, targets, data] = Load(
npm ERR!                                             ^^^^^
npm ERR!   File "/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 150, in Load
npm ERR!     result = gyp.input.Load(
npm ERR!              ^^^^^^^^^^^^^^^
npm ERR!   File "/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3021, in Load
npm ERR!     LoadTargetBuildFile(
npm ERR!   File "/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 411, in LoadTargetBuildFile
npm ERR!     build_file_data = LoadOneBuildFile(
npm ERR!                       ^^^^^^^^^^^^^^^^^
npm ERR!   File "/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
npm ERR!     build_file_contents = open(build_file_path, "rU").read()
npm ERR!                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! ValueError: invalid mode: 'rU' while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 22.6.0
npm ERR! gyp ERR! command "/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/bin/node" "/Users/mohamedawnallah/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/mohamedawnallah/Desktop/ihr-website/node_modules/deasync
npm ERR! gyp ERR! node -v v16.9.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! Build failed

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mohamedawnallah/.npm/_logs/2023-08-30T14_43_29_049Z-debug.log
```

**To Reproduce**
1) Install Python 3.11.4
2) Run the project using `npm install`
3) You will see this error

**Expected behavior**
Should run successfully or at least let the user know what the expected Python versions that the project supports

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
The main problem with `node-gyp`. [node-gyp](https://github.com/nodejs/node-gyp) is a cross-platform command-line tool written in Node.js for compiling native addon modules for Node.js. it is written mainly in Python and it supports only the following versions v3.7, v3.8, v3.9, or v3.10 as illustrated in the [npm docs](https://www.npmjs.com/package/node-gyp)

**Comment by romain-fontugne** [comment] 2023-09-06 02:24
I cannot really reproduce this error. I use Python 3.11.3 on my system and everything seems to work ok. I think the error you get is because they use the `U` mode to read files which has been deprecated. Maybe the problem should be fixed there.

**Comment by mohamedawnallah** [comment] 2023-09-06 07:27
What version of npm and node js you're using ?

Me the following:
```
➜  ihr-website git:(master) ✗ npm --version
7.21.1
➜  ihr-website git:(master) ✗ node --version
v16.9.1
```

**Comment by romain-fontugne** [comment] 2023-09-06 07:51
this:
```
ihr-website »  npm --version                                                                                 master ✔ 
8.19.4
ihr-website » node --version                                                                                 master ✔ 
v16.20.0
```

**Comment by mohamedawnallah** [comment] 2023-09-06 08:41
Yeah, this node js LTS version `v16.20.0` worked fine on all versions of Python `3.11.X`. I would suggest removing `Currently the project supports node --version =< 16.9.1` in the README and suggest this exact version to avoid any conflicts.

**Comment by romain-fontugne** [comment] 2023-09-07 01:31
yes, that makes sense

**Closed** 2023-09-07 01:32 UTC
Labels: documentation
