### ISSUE TITLE
Page refresh changes date back by one day

### ISSUE THREAD

**Issue by digizeph** [InternetHealthReport/ihr-website#162] opened 2022-07-14 02:32 UTC
**Describe the bug**
When looking at graph for a ASN with a time specified, the time automatically turns back by one day.

**To Reproduce**

1. Go to 'https://ihr.iijlab.net/ihr/en-us/networks/AS63346?rov_tb=routes&af=4&last=3&date=2022-07-09'
2. Refresh the page
3. The date goes back by one day.

**Expected behavior**
The date filter should not change on refresh.

**Screenshots**
The link for 2022-07-09 goes to 2022-07-08 on page load:
https://ihr.iijlab.net/ihr/en-us/networks/AS63346?rov_tb=routes&af=4&last=3&date=2022-07-09

<img width="816" alt="image" src="https://user-images.githubusercontent.com/659667/178885430-a3a328cf-3d2f-4d9b-a6c9-022e2c7eac75.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser Safari and Firefox

**Comment by priyansh71** [comment] 2022-10-15 19:06
I don't think this issue exists anymore. Can you check again?

**Comment by Aniket762** [comment] 2022-11-06 09:43
Hey @digizeph, it doesn't happen for me either. I have checked the behavior in Chrome, Safari, and Firefox. Maybe there was some cache issue at your end. 


Closing this issue. Incase you find it once again let me know I would reopen the issue. Thanks, for your help though. 

> **Describe the bug** When looking at graph for a ASN with a time specified, the time automatically turns back by one day.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'https://ihr.iijlab.net/ihr/en-us/networks/AS63346?rov_tb=routes&af=4&last=3&date=2022-07-09'
> 2. Refresh the page
> 3. The date goes back by one day.
> 
> **Expected behavior** The date filter should not change on refresh.
> 
> **Screenshots** The link for 2022-07-09 goes to 2022-07-08 on page load: https://ihr.iijlab.net/ihr/en-us/networks/AS63346?rov_tb=routes&af=4&last=3&date=2022-07-09
> 
> <img alt="image" width="816" src="https://user-images.githubusercontent.com/659667/178885430-a3a328cf-3d2f-4d9b-a6c9-022e2c7eac75.png">
> 
> **Desktop (please complete the following information):**
> 
> * OS: Mac
> * Browser Safari and Firefox

**Closed by Aniket762** 2022-11-06 09:43 UTC

**Comment by romain-fontugne** [comment] 2022-11-08 03:32
@Aniket762 are you on macOS?
I cannot reproduce that on linux but it could be a problem with Mac

**Comment by Aniket762** [comment] 2022-11-08 04:41
> @Aniket762 are you on macOS? I cannot reproduce that on linux but it could be a problem with Mac

I am on macOS but was not able to reproduce the problem as well.
